version: '3'
services:
  management_db:
    image: "postgres:9.6.17"
    container_name: 'management_db'
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=docker