version: '2.2'

services:
  management_db:
    image: postgres:9.6.17
    container_name: management_db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=docker
  
  kibana:
    image: kibana:7.16.1
    depends_on:
      elastic:
        condition: service_healthy
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  
  elastic:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  