version: '2.2'

services:

  # Management Api
  musihqa-management-api:
    build: Volkin.Musihqa.Management/
    container_name: 'musihqa-management-api'
    restart: always
    ports:
      - 8090:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker          
    depends_on:
      elastic:
        condition: service_healthy
      management-db:
        condition: service_healthy

  management-db:
    image: postgres:9.6.17
    container_name: management-db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=management_db
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  kibana:
    image: kibana:7.16.1
    depends_on:
      elastic:
        condition: service_healthy
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  
  elastic:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  